backend:
    name: git-gateway
    repo: scnroy/east-austin-book-club
    branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: site
    label: East Austin Book Club
    delete: false
    editor:
      preview: false
    files:
      - label: Content
        name: content
        file: content/content.yml
        fields:
          - { name: heading, label: Site Heading }
          - { name: tagline, label: Site tagline }
          - { name: intro, label: Introduction, widget: markdown }
          - { name: title, label: Meta Title }
          - { name: description, label: Meta Description }
  - name: books
    label: Books
    folder: content/books
    create: true
    preview: false
    slug: "{{title}}-{{date}}"
    editor:
      preview: false
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: author, label: Author }
      - { name: link, label: Link }
      - { name: cover, label: Book cover, widget: image }
      - { name: description, label: Description, widget: markdown }
      - { name: questions, label: Questions, widget: markdown }